- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 1800

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: dist

- name: Install packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - caffeine
    - transmission
    - cifs-utils
    - playonlinux
    - build-essential
    - maven
    - steam
    - rsync
    - flatpak

- name: Remove unused dependencies
  become: yes
  apt:
    autoremove: yes
