- include_tasks: repos.yml

- include_tasks: config.yml

- include_tasks: fixes.yml

- include_tasks: nas.yml

- include_tasks: hdd_crypttab.yml
  when: (secondary_volume_type == 'data') or (secondary_volume_type == 'home')

- include_tasks: hdd_data.yml
  when: secondary_volume_type == 'data'

- include_tasks: hdd_home.yml
  when: secondary_volume_type == 'home'
