- name: Create target directory
  file: path=/tmp/ansible/packages state=directory

- name: Download ESL package file
  get_url:
    url="https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
    dest="/tmp/ansible/packages/erlang-solutions_1.0_all.deb"

- name: Install ESL package
  become: yes
  apt: deb="/tmp/ansible/packages/erlang-solutions_1.0_all.deb"

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install erlang
  become: yes
  apt: pkg=esl-erlang

- name: Install elixir
  become: yes
  apt: pkg=elixir

- name: Remove ESL package file
  file: path="/tmp/ansible/packages/erlang-solutions_1.0_all.deb" state=absent
