- name: Install docker prerequisites
  become: yes
  apt: pkg={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add docker GPG key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install docker
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Create docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: yes
  user:
    name: "{{ target_user }}"
    groups: docker
    append: yes

- name: Enable docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
