- name: Install docker prerequisites
  become: yes
  apt: pkg={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add docker GPG key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} edge

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install docker
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
