---
- hosts: localhost

  vars:
    user_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - { role: base }
    - { role: env }
    - { role: flatpacks }
    - { role: sdkman }
    - { role: docker }
