- name: Retrieve partition information for primary device {{ primary_device }}
  become: yes
  parted: device="{{ primary_device }}" unit=MiB
  register: primary_part_info

- name: Delete existing partitions on primary device {{ primary_device }}
  become: yes
  parted:
    device: "{{ primary_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
   - "{{ primary_part_info.partitions }}"

- name: Create efi partition on primary devivce {{ primary_device }}
  become: yes
  parted:
    device: "{{ primary_device }}"
    flags: [esp]
    number: "{{ efi_partition_number }}"
    part_start: "{{ system_partition_offset }}MiB"
    part_end: "{{ system_partition_offset + system_partition_size }}MiB"
    part_type: primary
    state: present
  when: with_efi

- name: Create boot partition on primary devivce {{ primary_device }}
  become: yes
  parted:
    device: "{{ primary_device }}"
    flags: [boot]
    number: "{{ boot_partition_number }}"
    part_start: "{{ system_partition_offset + ((boot_partition_number | int - 1) * system_partition_size) }}MiB"
    part_end: "{{ system_partition_offset + (boot_partition_number | int * system_partition_size) }}MiB"
    part_type: primary
    state: present

- name: Create root partition on primary devivce {{ primary_device }}
  become: yes
  parted:
    device: "{{ primary_device }}"
    number: "{{ root_partition_number }}"
    part_start: "{{ system_partition_offset + (boot_partition_number | int * system_partition_size) }}MiB"
    part_end: 100%
    part_type: primary
    state: present

- name: Set facts for primary device {{ primary_device }}
  set_fact:
    primary_device_efi_partition_number: "{{ efi_partition_number }}"
    primary_device_boot_partition_number: "{{ boot_partition_number }}"
    primary_device_root_partition_number: "{{ root_partition_number }}"
